### ISSUE TITLE
Change guide from Region1 to Region2

### ISSUE THREAD

**Issue by CraigBoswell** [gdwaterworth/Home-Assistant---E-Linter-Logger---Sunsynk#53]
Apologies if there is a guide already which I have not found, but are there instructions for changes required to move from R1 to R2?
The instructions I find are for new installations, and not sure what should be deleted from existing setup to prepare for R2 setup.
Was really hoping to keep entities with same names etc. so automations can start to flow again.
Any assistance greatly appreciated.
I have a single Sunsynk 8.8kW inverter which was communicating 100% before the Region change.

**Comment by t0mtaylor** [comment]
@CraigBoswell have you changed the region attribute from 1 to 2 in the HA config?

Here is mine below in the Home Assistant Config, set to region 2

```
############################################
##### Main Config Sensor
############################################
  - sensor:
      - name: "SunSynk Config"
        state: "Config Sensor"
        unique_id: "sensor.sunsynk_config"
        attributes:
          login: !secret sunsynk_user
          password: !secret sunsynk_password
          region: 2
          invertor_list_opt: 0
          return_items: 10
          sn_data: !secret sunsynk_sn_data
          sn_flow: !secret sunsynk_sn_flow
          unit_cost: 0.45
          force_short_delay: "true"
```
